### ISSUE TITLE
Imamo problem sa preformanacama izvještaja 

### ISSUE THREAD

**Issue by adopilot** [adopilot/CCExchangeReport#5]
Ovo je postalo ne uptorvljico jer su nam preofmanse užasne

**Comment by adopilot** [comment]
Idemo prov opitmizirati ja sam dodao novi index koristeći

```
create index ix_cdr_call_date
on cdr (calldate)
```

![image](https://cloud.githubusercontent.com/assets/4448913/19212915/f3c54394-8d5d-11e6-8239-aa8f9028f6bb.png)

**Comment by adopilot** [comment]
@alensar daj molim te provjeri na svojoj bazi da li imaš index
`outgoing_dateteime_etnry` na tablici call_progres_logg
Meni optimizer javalja da koristiti indexe 
Najvejrovatnije ce mo morati reindexirati bazu da bi dolbili na brzini

![image](https://cloud.githubusercontent.com/assets/4448913/19212959/4c00d63a-8d5f-11e6-981d-995630314b1d.png)

**Comment by adopilot** [comment]
imamo uljeza to jeste našli smo ga 

```
/*explain extended*/
select 
 date(audit.datetime_init) as datum
,case when id_call_outgoing is not null then sum(second(audit.duration)) end as totalWrapUpForOutgoingCalls
,case when id_call_incoming is not null then sum(second(audit.duration)) end as totalWrapUpForIncomingCalls

from audit
inner join call_progress_log on audit.id_agent=call_progress_log.id_agent and audit.datetime_init=call_progress_log.datetime_entry
where id_break=9 
and call_progress_log.duration is not null
/*and  audit.datetime_init between  STR_TO_DATE('1-07-2016', '%d-%m-%Y') and  STR_TO_DATE('31-07-2016', '%d-%m-%Y') */
group by date(audit.datetime_init)
```

Smijem se zakleti da sam bio utrefio index koji ubrzava ovaj query ali ne znam kako 
jer ako ovaj dio ne ubrzamo izvještaj za period uvijek ce nam kašljati

**Comment by adopilot** [comment]
Evo ga i ovaj je riješen 

```
create index ix_audit_ado_tune
on audit (id_agent,datetime_init)
```

**Comment by adopilot** [comment]
evo mislim da je ovo gotovo 
ja sam optimizirao ova 3 x reporta koji govore o totalima poziova
razloge poziva ce mo optimizirati naknado hajde da ovo riješimo 
@alensar  Da bi ti opimizacija upsjela potrebno je da kriraš ove indexe

```
use asteriskcdrdb;
create index ix_cdr_call_date
on cdr (calldate);

use call_center_pro;
create index ix_call_entry_datetime_end
on call_center_pro (datetime_end);


use call_center_pro;
create index ix_audit_ado_tune
on audit (id_agent,datetime_init);
```

i potreno je da mimigraš ove 3 sproc sa novim kodovima

```
total_calls_for_period
total_cals_per_month
totoal_cals_per_day
```

Izmjene su vidjljive u ovom PR-u #4

**Comment by adopilot** [comment]
@alensar  još jednom mislim da smo preformse rijšili
https://github.com/adopilot/CCExchangeReport/commit/009abba7cd9d3f4fa7a195d8609b1c1f19cbf8c1

Ono što nam ostje da vidimo kakvi trebaju MAITANCE za MySql što se tiče indexa.
Ja kada održavam MSSQL-ove sa vremena na vrijeme moram ili rebuild ili reorganize indexe kako bi preformase držao na nivou-
Nemam dovoljno iskustava sa MySql bazama da li se trebaju održavati indexi 
Izgleda da ne trebaju makar po ovome što piše na ovom blogu 
Možeš li ti napraviti reasrch da vidimo šta nam je raditi sa indexima 

https://www.safaribooksonline.com/library/view/high-performance-mysql/0596003064/ch04s04.html

**Comment by adopilot** [comment]
Evo i gifa koji pokazje 
![brzina](https://cloud.githubusercontent.com/assets/4448913/19213264/2d1fd178-8d67-11e6-848b-d39af86ee640.gif)

**Comment by adopilot** [comment]
@alensar  deba nemoj ovo pustati u produkciju još imamo bug sa datumima
Napravio sam zajeb kada sam sada u srpcevima skunu funckiu date sa kolone datum da bi natjerao engin da koristi indexe sajebo sam se u smislu da sada nema podataka do datuma jer su kolone sa vremenom
evo ide PR za 10 minuta

**Comment by adopilot** [comment]
evo fixali smo i ovaj bugćić
spremno za produkciju 
https://github.com/adopilot/CCExchangeReport/commit/525b821248a03449419e3a1affca40400953c4b1

**Comment by alensar** [comment]
Oke druze. Mislio sam sutra nekada ali sacekam

**Comment by adopilot** [comment]
Rijesio sam ovo hoces li sutra da dkupa radimo upgrade meni je zena u
bolnici sa malom a ja djecu ostalu uvalim nani

Dana 8. 10. 2016. 20:15 osoba "alensar" notifications@github.com napisala
je:

> Oke druze. Mislio sam sutra nekada ali sacekam
>
